# Generated by Django 3.2 on 2021-06-12 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('hostName', models.CharField(blank=True, max_length=250, null=True)),
                ('hostOs', models.CharField(blank=True, max_length=250, null=True)),
                ('ip', models.CharField(blank=True, max_length=250, null=True)),
                ('disk', models.CharField(blank=True, max_length=250, null=True)),
                ('ram', models.CharField(blank=True, max_length=250, null=True)),
                ('cpu', models.CharField(blank=True, max_length=250, null=True)),
                ('interface', models.CharField(blank=True, max_length=250, null=True)),
                ('graphic', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
