# Generated by Django 3.2 on 2021-06-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Machine',
        ),
    ]
