# Generated by Django 3.2 on 2021-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_product_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='ip',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
