# Generated by Django 3.2 on 2021-06-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_machine_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='cpu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='disk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='graphic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ram',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
